pipeline {
    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven3'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/PapaBadara/HelloWebAppJavaTomcat.git'
            }
        }

        stage('Build') {
            steps {
                dir('HelloWorldWebApp') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Archive WAR') {
            steps {
                dir('HelloWorldWebApp') {
                    archiveArtifacts artifacts: 'target/*.war', fingerprint: true
                }
            }
        }

        stage('Deploy to Tomcat') {
            steps {
                dir('HelloWorldWebApp') {
                    deploy adapters: [
                        tomcat9(
                            credentialsId: 'tomcat-creds',
                            url: 'http://10.163.12.54:8081'
                        )
                    ],
                    contextPath: 'HelloWorldWebApp',
                    war: 'target/HelloWorldWebApp-1.0-SNAPSHOT.war'
                }
            }
        }
    }

    post {
        success {
            echo "✅ Build et déploiement réussis!"
        }
        failure {
            echo "❌ Erreur dans le pipeline!"
        }
    }
}
